export type {
  AlumnoBase,
  IncidenciaBase,
  NotificacionBase,
  PostulacionBase,
  ProcesoBase,
  VacanteBase,
} from "./types";
export type {
  AreaCatalogResponse,
  CartaMetadataResponse,
  DocumentoEstatusResponse,
  EscuelaResponse,
  TitularAreaCatalogResponse,
} from "./api-responses";
export { estatusBadgeIcon, estatusTone, formatEtiqueta, formatFecha, formatSiNo } from "./labels";
export {
  cartaTipoIncludes,
  resolveCartaDownloadKind,
  type CartaDownloadKind,
} from "./cartas";
export {
  HORA_CORRECCION_SOLO_ACTIVIDADES_ALUMNO,
  HORA_OBSERVAR_SOLO_ACTIVIDADES_DELEGACION,
  MAX_HORAS_ALUMNO_POR_DIA,
  calcularHorasEntre,
  isFechaRegistroHoy,
  validarRegistroHoraAlumno,
} from "./horas";
export {
  ALUMNO_CV_NAV_ID,
  ALUMNO_NAV_IDS_BLOCKED_WITHOUT_CV,
  CV_OPTIONAL_FIELDS,
  CV_REQUIRED_FIELDS,
  CV_TRACKED_FIELDS,
  countCvProgress,
  isCvComplete,
  type CvCompletionSnapshot,
  type CvRequiredField,
  type CvTrackedField,
} from "./cv";
export {
  formatHorasProceso,
  isListoParaActivacion,
  puedeActivarProceso,
  tieneHorasRequeridas,
  canCancelProceso,
  canEmitCartaAceptacion,
  canEmitCartaLiberacion,
  canEmitirLiberacionTecnica,
  canRegistrarEvaluacionFinal,
  mensajeBloqueoEvaluacionFinal,
  mensajeBloqueoLiberacionTecnica,
  procesoEfectivamenteHorasCompletas,
  procesoHorasNumericamenteCompletas,
  procesoPendienteEstatusHorasCompletas,
  canRegistrarHoraProceso,
  canRegistrarIncidenciaProceso,
  canSetHorasRequeridas,
  EVALUACION_FINAL_ESTATUS,
  EVALUACION_FINAL_ESTATUS_LABELS,
  isProcesoActivo,
  puedePostularVacantes,
  type FormatHorasProcesoStyle,
} from "./proceso";
export {
  canAlumnoActualizarBitacora,
  canAlumnoDescargarDocumento,
  canAlumnoSubirDocumento,
  canApproveDocumento,
  canObserveDocumento,
  canRejectDocumento,
  canReviewDocumento,
} from "./documento";
export {
  canCancelHora,
  canObserveHora,
  canRejectHora,
  canValidateHora,
  isHoraPendienteRevision,
} from "./horas";
export { canCancelIncidencia, canResolveIncidencia, INCIDENCIA_TIPOS_RESOLUCION, INCIDENCIA_TIPO_RESOLUCION_LABELS } from "./incidencia";
export {
  canAcceptPostulacion,
  canCancelPostulacion,
  canContestarExamen,
  canMarkPostulacionExam,
  canRejectPostulacion,
  getCancelPostulacionConfirmMessage,
  isExamenFinalizado,
  isPostulacionResuelta,
  tieneExamenPorContestar,
} from "./postulacion";
export {
  canCancelVacanteTitular,
  canCloseVacanteDelegacion,
  canEditVacanteTitular,
  canPublishVacanteDelegacion,
  canRejectVacanteDelegacion,
  canSendVacanteToReview,
  getModalidadTrabajoLabel,
  isVacantePendienteRevision,
  MODALIDAD_TRABAJO_OPTIONS,
  type ModalidadTrabajoValue,
} from "./vacante";
export {
  getModalidadCatalogoLabel,
  isValidModalidadCatalogo,
  MODALIDAD_CATALOGO_OPTIONS,
  type ModalidadCatalogoValue,
} from "./modalidad";
export { normalizeDomainCode, readEntityEstatus } from "./status";
export {
  EXAMEN_ESTATUS,
  PREGUNTA_TIPO,
  PREGUNTA_TIPO_OPTIONS,
  formatPreguntaTipo,
  formatPuntajeMinimo,
  formatTiempoLimite,
  getPreguntasActivas,
  isExamenActivo,
  isExamenBorrador,
  preguntaTieneRespuestaValida,
  puedeActivarExamen,
  type ExamenEstatus,
  type PreguntaTipo,
  type ExamenOpcionResponse,
  type ExamenPreguntaResponse,
  type ExamenDiagnosticoResumenResponse,
  type ExamenDiagnosticoDetalleResponse,
  type CrearExamenDiagnosticoRequest,
  type ActualizarExamenDiagnosticoRequest,
  type ExamenOpcionRequest,
  type ExamenPreguntaRequest,
  type AsociarExamenVacanteRequest,
  type AlumnoExamenOpcionResponse,
  type AlumnoExamenPreguntaResponse,
  type AlumnoExamenDisponibleResponse,
  type IntentoExamenResponse,
  type RespuestaExamenRequest,
  type FinalizarExamenRequest,
  type FinalizarExamenResponse,
  type ResultadoExamenRespuestaResponse,
  type ResultadoExamenResponse,
} from "./examen";
export type {
  AceptarPostulacionRequest,
  CancelarHoraRequest,
  CancelarIncidenciaRequest,
  CancelarProcesoRequest,
  ComentarioOpcionalRequest,
  ComentarioRequest,
  CrearEvaluacionFinalRequest,
  CrearIncidenciaRequest,
  EmitirLiberacionTecnicaRequest,
  ExamenFinalizadoRequest,
  MotivoRequest,
  ObservarHoraRequest,
  RechazarHoraRequest,
  RechazarPostulacionRequest,
  RechazarVacanteRequest,
  RegistrarHoraInternaRequest,
  ResolverIncidenciaRequest,
  ValidarDocumentoRequest,
  ValidarHoraRequest,
} from "./requests";
